pipeline:
  create_cluster:
    image: banzaicloud/plugin-pipeline-client:latest
    cluster_name: "pdicluster07"
    cluster_provider: "google"
    google_project: "puski-test-194413"
    google_gke_version: "1.8.7-gke.1"
    google_node_count: "2"
    google_service_account: "lp-sa-580@puski-test-194413.iam.gserviceaccount.com"
    log_level: "debug"

    secrets: [plugin_endpoint, plugin_token]

  install_monitoring:
    image: banzaicloud/plugin-pipeline-client:latest
    deployment_name: "banzaicloud-stable/pipeline-cluster-monitor"
    deployment_release_name: "monitor"

    secrets: [plugin_endpoint, plugin_token]
    
  install_zeppelin:
    image: banzaicloud/plugin-pipeline-client:latest
    deployment_name: "banzaicloud-stable/zeppelin-spark"
    deployment_release_name: "release-1"
    deployment_state: "created"
    deployment_values:
      zeppelin:
        sparkSubmitOptions:
          eventLogDirectory: "gs://puski-testing/data"
      historyServer:
        enabled: true
      spark:
        spark-hs:
          app:
            logDirectory: "gs://puski-testing/data"
    secrets: [plugin_endpoint, plugin_token]
  
  remote_checkout:
    image: banzaicloud/drone-plugin-k8s-client:latest
    original_image: plugins/git

  run:
    image: banzaicloud/drone-plugin-k8s-client:latest
    original_image: banzaicloud/zeppelin-client:test
    log_level: "debug"
    notebook_name: "sf-police-incidents"
    notebook_file_path: "sf-police-incidents-gke.json"
    notebook_state: "running"
    zeppelin_endpoint: "http://release-1-zeppelin:8080/zeppelin"

